;---------------------------------------------------------------------------
; webp.datatype - exec library / BOOPSI class library startup
;
; Same scheme as EmojiGear's libutf8rastport & gadgets: this file is linked
; first (see amiga_library.ld), the binary is produced as an "executable"
; with -nostartfiles -Wl,-e,__start, and exec finds the RomTag in the hunk.
;
; A datatype is a class library whose first public vector (-30) is
; ObtainEngine(), returning the Class pointer that datatypes.library
; uses with NewObject().
;---------------------------------------------------------------------------

        NOLIST

        INCLUDE "exec/types.i"
        INCLUDE "exec/libraries.i"
        INCLUDE "exec/lists.i"
        INCLUDE "exec/alerts.i"
        INCLUDE "exec/initializers.i"
        INCLUDE "exec/resident.i"
        INCLUDE "libraries/dos.i"
        INCLUDE "utility/hooks.i"
        INCLUDE "intuition/classes.i"

        LIST

        ; generated by cmake configure_file() into the build dir
        INCLUDE "libversion.i"

_LVORemove      EQU     -252
_LVOFreeMem     EQU     -210
_LVOStackSwap   EQU     -732

 ifnd cl_Pad
  STRUCTURE ClassLibrary,0
    STRUCT       cl_Lib,LIB_SIZE        ; Embedded library
    UWORD        cl_Pad                 ; Align the structure
    APTR         cl_Class               ; Class pointer
    LABEL        ClassLibrary_SIZEOF
 endc

        ; what is actually allocated as the library base.
        ; C side only uses the struct ClassLibrary part.
        STRUCTURE ExtClassLib,0
                STRUCT  cb_ClassLibrary,ClassLibrary_SIZEOF
                ULONG   cb_SysBase
                ULONG   cb_SegList
        LABEL ClassLib_SIZEOF

CALL    MACRO
        jsr     _LVO\1(a6)
        ENDM

;---------------------------------------------------------------------------

        XREF    _CLibInit
        XREF    _CLibExpunge
        XREF    _Lib_ID
        XREF    _VersionString

;---------------------------------------------------------------------------

        ; Dedicated section so the linker script places this block first.
        SECTION __libinit,CODE

        XDEF    __start

; First executable location, must return an error if run as a command.
__start:
        moveq   #-1,d0
        rts

;---------------------------------------------------------------------------

RomTag:
        DC.W    RTC_MATCHWORD           ; UWORD RT_MATCHWORD
        DC.L    RomTag                  ; APTR  RT_MATCHTAG
        DC.L    EndCode                 ; APTR  RT_ENDSKIP
        DC.B    RTF_AUTOINIT            ; UBYTE RT_FLAGS
        DC.B    VERSION                 ; UBYTE RT_VERSION
        DC.B    NT_LIBRARY              ; UBYTE RT_TYPE
        DC.B    0                       ; BYTE  RT_PRI
        DC.L    _Lib_ID                 ; APTR  RT_NAME
        DC.L    _VersionString          ; APTR  RT_IDSTRING
        DC.L    LibInitTable            ; APTR  RT_INIT

        CNOP    0,4

LibInitTable:
        DC.L    ClassLib_SIZEOF
        DC.L    LibFuncTable
        DC.L    0
        DC.L    LibInit

LibFuncTable:
        DC.L    LibOpen
        DC.L    LibClose
        DC.L    LibExpunge
        DC.L    LibNull
        DC.L    ObtainEngine            ; -30: Class *ObtainEngine(void)
        DC.L    -1

;---------------------------------------------------------------------------
        XDEF _SysBase
_SysBase:
SysBase:        DC.L 0

; On entry, D0 = library base, A0 = seglist, A6 = SysBase.
; Returns 0 for failure or the library base for success.
LibInit:
        move.l  a5,-(sp)
        move.l  d0,a5
        move.l  a6,cb_SysBase(a5)
        move.l  a6,SysBase
        move.l  a0,cb_SegList(a5)
        move.w  #VERSION,LIB_VERSION(a5)
        move.w  #REVISION,LIB_REVISION(a5)
        clr.w   LIB_OPENCNT(a5)
        clr.l   cl_Class(a5)
        move.l  a5,d0
        move.l  (sp)+,a5
        rts

;---------------------------------------------------------------------------
; OpenLibrary(): A6 = library base, under Forbid().
; CLibInit(base) opens system libs and creates the class the first time;
; it returns 0 on success.
LibOpen:
        move.l  a6,-(sp)
        jsr     _CLibInit
        addq.l  #4,sp
        tst.l   d0
        beq.s   .ok
        moveq   #0,d0
        rts
.ok:
        addq.w  #1,LIB_OPENCNT(a6)
        bclr    #LIBB_DELEXP,LIB_FLAGS(a6)
        move.l  a6,d0
        rts

;---------------------------------------------------------------------------
; CloseLibrary(): returns seglist if a delayed expunge can now happen.
LibClose:
        subq.w  #1,LIB_OPENCNT(a6)
        bne.s   .stay
        btst    #LIBB_DELEXP,LIB_FLAGS(a6)
        bne.s   DoExpunge
.stay:
        moveq   #0,d0
        rts

;---------------------------------------------------------------------------
; Expunge: only when nobody has us open, and CLibExpunge() agrees
; (FreeClass() fails while objects of our class are still alive).
LibExpunge:
        tst.w   LIB_OPENCNT(a6)
        beq.s   DoExpunge
        bset    #LIBB_DELEXP,LIB_FLAGS(a6)
        moveq   #0,d0
        rts

DoExpunge:
        movem.l d2/a5/a6,-(sp)
        move.l  a6,a5

        move.l  a5,-(sp)
        jsr     _CLibExpunge
        addq.l  #4,sp
        tst.l   d0
        bne.s   .free
        bset    #LIBB_DELEXP,LIB_FLAGS(a5)
        moveq   #0,d0
        bra.s   .out
.free:
        move.l  cb_SysBase(a5),a6
        move.l  cb_SegList(a5),d2
        move.l  a5,a1
        CALL    Remove
        move.l  a5,a1
        moveq   #0,d0
        move.w  LIB_NEGSIZE(a5),d0
        sub.l   d0,a1
        add.w   LIB_POSSIZE(a5),d0
        CALL    FreeMem
        move.l  d2,d0
.out:
        movem.l (sp)+,d2/a5/a6
        rts

LibNull:
        moveq   #0,d0
        rts

;---------------------------------------------------------------------------
; Class *ObtainEngine(void), A6 = library base.
ObtainEngine:
        move.l  cl_Class(a6),d0
        rts

;---------------------------------------------------------------------------
; ULONG WebpCallWithStack(ULONG (*func)(APTR), APTR arg,
;                         struct StackSwapStruct *sss)
; Runs func(arg) on the stack described by sss (exec StackSwap, V37).
; Datatype methods run on the caller's stack, which may be only 4KB.
        XDEF    _WebpCallWithStack
_WebpCallWithStack:
        movem.l d2/a2-a3/a6,-(sp)
        move.l  20(sp),a2               ; func
        move.l  24(sp),d2               ; arg
        move.l  28(sp),a3               ; sss
        move.l  SysBase,a6
        move.l  a3,a0
        CALL    StackSwap
        move.l  d2,-(sp)
        jsr     (a2)
        addq.l  #4,sp
        move.l  d0,d2
        move.l  SysBase,a6
        move.l  a3,a0
        CALL    StackSwap
        move.l  d2,d0
        movem.l (sp)+,d2/a2-a3/a6
        rts

;---------------------------------------------------------------------------
EndCode:
        END
